services:
  database:
    image: "postgres:17.6"
    ports:
      - 5432:5432
    volumes:
      - /home/r3d5un/Development/Data/PostgreSQL/data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
