apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/immich
    type: DirectoryOrCreate
