apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: immich
  name: immich-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: immich-pv
