apiVersion: v1
kind: Service
metadata:
  name: immich-service
  namespace: immich
spec:
  type: NodePort
  selector:
    app: immich
  ports:
    - nodePort: 31130
      port: 2203
      targetPort: 2203
