apiVersion: v1
kind: Namespace
metadata:
  name: kavita
  labels:
    app: kavita
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-videos-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: kavita
  labels:
    app: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
      - name: kavita
        image: jellyfin/jellyfin:10.11
        ports:
        - containerPort: 8096
        - containerPort: 7359
        

