apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: forgejo
  name: forgejo-pvc
spec:
  storageClassName: homelab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
