apiVersion: v1
kind: ConfigMap
metadata:
  name: forgejo-configmap
  namespace: forgejo
  labels:
    app: forgejo
data:
  USER_UID: "1000"
  USER_GID: "1000"
  FORGEJO__database__DB_TYPE: "postgres"
  FORGEJO__database__HOST: "10.0.0.9"
  FORGEJO__database__NAME: "forgejo"
  FORGEJO__database__USER: "forgejo"
  FORGEJO__server__ROOT_URL: "http://10.0.0.9:31170"
