apiVersion: apps/v1
kind: Deployment
metadata:
  name: forgejo
  namespace: forgejo
  labels:
    app: forgejo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forgejo
  template:
    metadata:
      labels:
        app: forgejo
    spec:
      containers:
        - name: forgejo
          image: codeberg.org/forgejo/forgejo:14
          envFrom:
            - configMapRef:
                name: forgejo-configmap
            - secretRef:
                name: forgejo-secrets
          ports:
            - containerPort: 3000
              name: http
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: forgejo-data
              mountPath: /data
            - name: localtime
              mountPath: /etc/localtime
              readOnly: true
      volumes:
        - name: forgejo-data
          persistentVolumeClaim:
            claimName: forgejo-pvc
        - name: localtime
          hostPath:
            path: /etc/localtime
      resources:
        limits:
          memory: "2Gi"
          cpu: "2"
        requests:
          memory: "512Mi"
          cpu: "500m"
