apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/forgejo
    type: DirectoryOrCreate
