apiVersion: v1
kind: PersistentVolume
metadata:
  name: homer-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/homer/assets
    type: DirectoryOrCreate
