return { -- Highlight, edit, and navigate code
	"nvim-treesitter/nvim-treesitter",
	build = ":TSUpdate",
	cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
	opts = {
		indent = { enable = true },
		highlight = { enable = true },
		ensure_installed = {
			"bash",
			"c",
			"html",
			"lua",
			"markdown",
			"vim",
			"vimdoc",
			"go",
			"rust",
			"python",
			"json",
			"sql",
			"yaml",
			"cpp",
			"javascript",
			"typescript",
			"r",
			"dockerfile",
			"css",
			"markdown_inline",
			"regex",
			"query",
			"http",
			"c_sharp",
			"java",
			"toml",
			"vue",
		},
	},
}
