return {
	"nvim-treesitter/nvim-treesitter",
	lazy = false,
	build = ":TSUpdate",
	event = { "BufReadPost", "BufNewFile" },
	cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
	opts = {
		ensure_installed = {
			"bash",
			"c",
			"html",
			"lua",
			"markdown",
			"vim",
			"vimdoc",
			"go",
			"rust",
			"python",
			"json",
			"sql",
			"yaml",
			"cpp",
			"javascript",
			"typescript",
			"r",
			"dockerfile",
			"css",
			"markdown_inline",
			"regex",
			"query",
			"http",
			"c_sharp",
			"java",
			"toml",
			"vue",
		},
		auto_install = true,
		highlight = { enable = true },
		indent = { enable = true },
		folds = { enable = true },
	},
}
