apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: calibre
  name: calibre-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: calibre-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: calibre
  name: calibre-books-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ""
  volumeName: calibre-books-pv
