apiVersion: v1
kind: Service
metadata:
  name: calibre-service
  namespace: calibre
spec:
  type: NodePort
  selector:
    app: calibre
  ports:
    - nodePort: 31190
      port: 8083
      targetPort: 8083
