apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: valkey
  name: valkey-pvc
spec:
  storageClassName: homelab
  accessModes: [ReadWriteOnce]
  resources: { requests: { storage: 5Gi } }
