apiVersion: v1
kind: Service
metadata:
  name: freshrss-service
  namespace: freshrss
spec:
  type: NodePort
  selector:
    app: freshrss
  ports:
    - nodePort: 31180
      port: 80
      targetPort: 80
