apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: freshrss
  name: freshrss-data-pvc
spec:
  storageClassName: homelab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: freshrss
  name: freshrss-extensions-pvc
spec:
  storageClassName: homelab
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
