apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss-deployment
  namespace: freshrss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
        - name: freshrss
          image: freshrss/freshrss:1-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: CRON_MIN
              valueFrom:
                configMapKeyRef:
                  name: freshrss-configmap
                  key: CRON_MIN
          volumeMounts:
            - name: freshrss-data
              mountPath: /var/www/FreshRSS/data
            - name: freshrss-extensions
              mountPath: /var/www/FreshRSS/extensions
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data-pvc
        - name: freshrss-extensions
          persistentVolumeClaim:
            claimName: freshrss-extensions-pvc
      resources:
        limits:
          memory: "512Mi"
          cpu: "1"
        requests:
          memory: "256Mi"
          cpu: "100m"
