apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: freshrss
  name: freshrss-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: freshrss-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: freshrss
  name: freshrss-extensions-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: freshrss-extensions-pv
