apiVersion: v1
kind: Namespace
metadata:
  name: postgresql
  namespace: postgresql
  labels:
    app: postgresql
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: postgresql
  name: pv-postgresql
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 25Gi
  hostPath:
    path: /home/r3d5un/Development/Kubernetes/Data/pv-postgresql/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: postgresql
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 25Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: postgresql
  labels:
    app: postgresql
data:
  postgresql-db: postgres
---
apiVersion: v1
kind: Secret
metadata:
  namespace: postgresql
  name: "postgresql-secrets"
type: Opaque
data:
  postgresql-user: cG9zdGdyZXM=
  postgresql-password: cG9zdGdyZXM=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:17.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgresql-configmap
                  key: postgresql-db
                  optional: false
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: postgresql-user
                  optional: false
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secrets
                  key: postgresql-password
                  optional: false
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "2000m"
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgresql-pvc
        - name: dshm
          emptyDir:
            sizeLimit: 4096Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: postgresql
  labels:
    app: postgresql
spec:
  type: NodePort
  ports:
    - nodePort: 31432
      port: 5432
  selector:
    app: postgresql
