apiVersion: apps/v1
kind: Deployment
metadata:
  name: kavita
  namespace: kavita
  labels:
    app: kavita
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kavita
  template:
    metadata:
      labels:
        app: kavita
    spec:
      containers:
        - name: kavita
          image: ghcr.io/kareadita/kavita:0.9.0.2
          env:
            - name: TZ
              value: "Europe/Oslo"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: config-volume
              mountPath: /kavita/config
            - name: manga-volume
              mountPath: /manga
            - name: comics-volume
              mountPath: /comics
            - name: books-volume
              mountPath: /books
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: kavita-config-pvc
        - name: manga-volume
          persistentVolumeClaim:
            claimName: kavita-manga-pvc
        - name: comics-volume
          persistentVolumeClaim:
            claimName: kavita-comics-pvc
        - name: books-volume
          persistentVolumeClaim:
            claimName: kavita-books-pvc
      resources:
        limits:
          memory: "4Gi"
          cpu: "2"
        requests:
          memory: "1Gi"
          cpu: "500m"
