apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: kavita-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: kavita-config-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: kavita-manga-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: kavita-manga-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: kavita-comics-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: kavita-comics-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: kavita-books-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
  storageClassName: ""
  volumeName: kavita-books-pv
