apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: kavita-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-hdd
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: kavita-manga-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-hdd
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: kavita-comics-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-hdd
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: kavita
  name: kavita-books-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: homelab-hdd
  resources:
    requests:
      storage: 100Gi
