apiVersion: v1
kind: PersistentVolume
metadata:
  name: kavita-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/kavita/config
    type: DirectoryOrCreate
